version: '2'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django
    command: ./prepare.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - rabbit

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - C_FORCE_ROOT="yes"
    command: ./run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit

