# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestCrawling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='request_crawling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.RequestCrawling'),
        ),
        migrations.AddField(
            model_name='creationtime',
            name='request_crawling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.RequestCrawling'),
        ),
    ]
